-- 전체 컬럼 조회
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

-- 특정 컬럼만 조회
-- 문자/날짜는 왼쪽, 숫자는 오른쪽
SELECT FIRST_NAME, HIRE_DATE, EMAIL, SALARY FROM EMPLOYEES;

-- PK는 EMPLOYEE_ID, FK는 DEPARTMENT_ID
SELECT FIRST_NAME, SALARY + SALARY * 0.1 FROM EMPLOYEES;

-- 엘리어스(별칭)
SELECT FIRST_NAME AS 별칭, SALARY 급여, SALARY + SALARY * 0.1 "최종 급여" FROM EMPLOYEES;

-- 문자열 연결 ||
-- 홑따옴표 안에서 홑따옴표를 쓰고 쓰고 싶다면 "'
SELECT 'HELLO' || ' WORLD' FROM EMPLOYEES;
SELECT FIRST_NAME || '''님의 급여는 ' || SALARY || '$입니다' AS 급여 FROM EMPLOYEES;

-- DISTINCT (중복 제거) 키워드
SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- ROWID(레코드 저장 위치), ROWNUM(조회순서)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;

-- 수정