--가상 테이블 dual
SELECT 'HELLO WORLD' FROM DUAL;

SELECT LOWER(FIRST_NAME), UPPER(FIRST_NAME), INITCAP (FIRST_NAME) FROM EMPLOYEES;

-- LENGTH 문자열 길이
SELECT FIRST_NAME, LENGTH (FIRST_NAME) FROM EMPLOYEES;

-- SUBSTR 문자열 자르기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 3), SUBSTR(FIRST_NAME, 3, 2) FROM EMPLOYEES; -- 3미만 절삭, 3번째 위치에서 2개 자름

-- CONCAT 문자열 합치기
SELECT FIRST_NAME || LAST_NAME, CONCAT(FIRST_NAME, LAST_NAME) FROM EMPLOYEES;

-- LPAD, RPAD - 범위를 지정하고, 특정문자로 채움
SELECT LPAD('ABC', 10, '*') FROM DUAL; -- ABC를 10칸 잡고, 나머지 부분은 왼쪽에서 * 채움
SELECT LPAD(FIRST_NAME, 10, '*'), RPAD(FIRST_NAME, 10, '-') FROM EMPLOYEES; -- 오른쪽에서 - 채움

-- LTRIM, RTRIM, TRIM - 공백삭제 또는 문자삭제
SELECT TRIM(' HELLO WORLD '), LTRIM(' HELLO WORLD'), RTRIM (' HELLO WORLD ') FROM DUAL;
SELECT LTRIM('HELLO WORLD', 'HE') FROM DUAL;